name: image_resizer
description: A sample Functions Framework project for handling a cloudevent.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework:
    git:
      url: https://github.com/nickmeinhold/functions-framework-dart
      path: functions_framework
      ref: null-safe
  shelf: any
  json_annotation: any
  googleapis: ^2.0.0
  googleapis_auth: ^1.0.0

dev_dependencies:
  build_runner: any
  functions_framework_builder:
    # We need the builder to add // @dart=2.9 to server.dart for no-sound-null-safety
    git:
      url: https://github.com/nickmeinhold/functions-framework-dart
      path: functions_framework_builder
      ref: null-safe
  http: any
  test: any
  test_process: any
  json_serializable: any