name: image_resizer
description: A sample Functions Framework project for handling a cloudevent.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  io: ^1.0.0
  functions_framework:
    git:
      url: git@github.com:GoogleCloudPlatform/functions-framework-dart.git
      path: functions_framework

dependencies:
  functions_framework:
    git:
      url: git@github.com:GoogleCloudPlatform/functions-framework-dart.git
      path: functions_framework
  shelf: any
  json_annotation: any
  googleapis: ^2.0.0
  googleapis_auth: ^1.0.0

dev_dependencies:
  build_runner: any
  functions_framework_builder:
    git:
      url: git@github.com:GoogleCloudPlatform/functions-framework-dart.git
      path: functions_framework_builder
  http: any
  test: any
  test_process: any
  json_serializable: any