name: dartimageresize
description: A sample Functions Framework project for handling a cloudevent.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependency_overrides:
  # In order to use null-safe freezed, version solving needed to have functions_framework migrated and importing null-safe json_annotation
  functions_framework:
    git:
      url: https://github.com/nickmeinhold/functions-framework-dart
      path: functions_framework
      ref: null-safe
  # because build_runner depends on old versions
  http: ^0.13.0-nullsafety.0
  http_parser: ^4.0.0-nullsafety
  shelf: ^1.0.0-nullsafety.0

dependencies:
  functions_framework: any
  shelf: ^1.0.0-nullsafety.0
  json_annotation: ^4.0.0-nullsafety.0

dev_dependencies:
  build_runner: any
  functions_framework_builder:
    # We need the builder to add // @dart=2.9 to server.dart for no-sound-null-safety
    git:
      url: https://github.com/nickmeinhold/functions-framework-dart
      path: functions_framework_builder
      ref: null-safe
  http: ^0.13.0-nullsafety.0
  test: ^1.16.0-nullsafety.16
  test_process: any
  json_serializable: ^4.0.0-nullsafety.0
